### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by Pratham0234** [codingelle/django-whatsapp-web-clone#12]
<html>
<body>
<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px 0px 0.4em; font-weight: normal;">Page not found<span> </span><span style="padding: 0px; margin: 0px; font-size: 15.6px; color: rgb(102, 102, 102); font-weight: normal;">(404)</span></h1>

Request Method: | GET
-- | --
http://127.0.0.1:8000/accounts/login/?next=/chat/

</div><div id="info" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(246, 246, 246); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">Using the URLconf defined in<span> </span><code style="padding: 0px; margin: 0px;">django_channel_tutorial.urls</code>, Django tried these URL patterns, in this order:</p><ol style="padding: 0px; margin: 0.5em 4em;"><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">chat/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">^media/(?P&lt;path&gt;.*)$</li></ol><p style="padding: 0px; margin: 0px;">The current path,<span> </span><code style="padding: 0px; margin: 0px;">accounts/login/</code>, didn’t match any of these.</p></div>
</body>

<h1>im new at this pls help</h1>
</html>

**Comment by josnin** [comment]
@Pratham0234  In this demo, There's  no accounts/login url

instead, u can use Django admin to create user and login

**Comment by Pratham0234** [comment]
Yes got the thing thanks
